###########
# site.title

title:    "Yuki's Center"
subtitle: 'yuki ...'

nav:
- { title: 'Accueil',              href: '/' }
- { title: 'Page de test',              href: '/test' }


markdown: kramdown

sass:
  sass_dir: css
  style:    expanded